version: '3'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sam@123
      MYSQL_DATABASE: sam
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis
    ports:
      - 6379:6379
